# Numpy Module

``` Channel Video : https://youtu.be/QEELEG99fV0 ```

In [ ]:
# importing Numpy
import numpy as np

In [ ]:
# Creating 0d Arraay - Scalar array

# the array() parameter have only one number it mwans the array is scalar array else it will call 0th D array

arr1 = np.array(5)
arr1

In [ ]:
# Creating 1 D array

# if we pass the list() into the array() it will known as one D array

a = np.array([1,2,3,4])
a

In [14]:
# Creating 1 D array

# if we pass the [[],[]] into the array() it will known as one D array

b = np.array([[1,2,3],[1,2,3]],dtype=int) # if we use 2d or 3d array it will be order in 2d array [[1,2],[1,2]] in the following example the list contain 2 elements each list... hence we will use same length values in the all of list 
b

# Dtype is use to Spcify the DataType of the all of the array in the NpArray

array([[1, 2, 3],
       [1, 2, 3]])

In [7]:
type(a) # ndarraay "nd" means "N" Dymantinal Array  

numpy.ndarray

In [16]:
a.ndim # ndim is used to find the Dymantinal of the array
b.ndim

2

In [18]:
# 3DArray

three = np.array([[[1,2,3]]
                 ,[[1,3,3]]
                 ,[[1,2,3]]])

three


array([[[1, 2, 3]],

       [[1, 3, 3]],

       [[1, 2, 3]]])

In [20]:
# Definind the Dimentsions

x1 = np.array([1,2,3,4],ndmin=6)
x1
#"ndmin" are used to set the dimantinal of the array

array([[[[[[1, 2, 3, 4]]]]]])

In [21]:
# Creating array of zero
zeros = np.zeros((2,3))
zeros

# 2 mention the "rows" and three metions "col"

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# Creating array of onse
x=np.ones((4,4))
x

# 4 mention the "rows" and 4 metions "col"


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# Eye Function : Returns array filled with zeros except in the kth diagonal, whose values are equal to 1

# Eyedantity means diagonal position onse is called "eye"

eye = np.eye(4)
eye

# the parameter mentions the N X N matrix 4 means 4X4 matrix

# also we can create eye(row,col)
x2 = np.eye(2,4)
x2


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [26]:
a = np.eye(4,k=-1) # k means diagonal position
a

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [27]:
a1 = np.eye(5,k=2) #  it's  control the position of diagonal
a1

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Assing Array Elements

In [ ]:
# Accessing 1d array

b = np.array([1,2])


In [32]:
# 3DArray

three = np.array([[[1,2,3]]
                 ,[[1,3,3]]
                 ,[[1,2,3]]])

three[0,0,2] # if we asscessing multi dim we can use "," seperated access

3

# Slicing Array

In [34]:
a = np.array([1,5,4,3,7,6,54,89])
print(a[0:3])
print(a[2:])
print(a[:4])

[1 5 4]
[ 4  3  7  6 54 89]
[1 5 4 3]


In [37]:
# slicing 2d array
a1 = np.array([[1,5,4,3,7,6,54,89],[1,5,4,3,7,6,54,89],[1,5,4,3,7,6,54,89]])

print(a1[0:2,:4])
print(a1[0:2,0:3])

[[1 5 4 3]
 [1 5 4 3]]
[[1 5 4]
 [1 5 4]]


# Numpy DataTypes

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

In [42]:
# To Convert Data Types

arr = np.array([1.1, 2.1, 3.1],dtype=int)

newarr = arr.astype('f')

print(newarr)
print(newarr.dtype)

[1. 2. 3.]
float32


In [43]:
# Make a copy, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [44]:
# Make a view, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]


# Array Shape

In [45]:
# NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [46]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [57]:
# Reshaping means changing the shape of an array.

# The shape of an array is the number of elements in each dimension.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(6, 2)

print(newarr)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [58]:
# Convert the following 1-D array with 12 elements into a 3-D array.

# The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [59]:
# Convert the array into a 1D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


# Iterating Arrays

In [60]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [61]:
# Iterate on the elements of the following 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [62]:
# Iterate on the elements of the following 3-D array:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [63]:
# Iterate down to the scalars:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [66]:
# Iterate through the following 3-D array:

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [69]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [70]:
# Enumerated Iteration Using ndenumerate()

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
